import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Link from "next/link";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [address, setAddress] = useState(null);
  async function connectToMetamask() {
    if (window.ethereum) {
      try {
        // Request account access from the user
        const accounts = await window.ethereum.request({
          method: "eth_requestAccounts",
        });
        setAddress(accounts[0]);
      } catch (err) {
        console.error(err);
      }
    } else {
      console.error("Metamask not found");
    }
  }

  return (
    <>
      <Head>
        <title>MedicalRoom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.background}>
        <main className={styles.main}>
          <div className={styles.grid}>
            <a
              href="#"
              onClick={() => {
                if (window.ethereum) {
                  window.ethereum.request({ method: "eth_requestAccounts" });
                }
              }}
              className={styles.card}
            >
              {address ? (
                <p>Connected to {address}</p>
              ) : (
                <h2 className={styles.meta}>
                  <div className={styles.imageContainer}>
                    <Image
                      className={styles.metalogo}
                      src="https://i.im.ge/2023/02/21/7XVFgh.OIP-1-removebg-preview.png"
                      alt="Next.js Logo"
                      width={50}
                      height={50}
                      priority
                    />
                  </div>
                  <button
                    className={styles.metamaskbutton}
                    onClick={connectToMetamask}
                  >
                    Connect to Metamask
                  </button>{" "}
                </h2>
              )}
            </a>
          </div>
          <div className={styles.containerd}>
            <div className={styles.rowd}>
              <div className={styles.column1d}>
                <div className={styles.imaged}>
                  <Image
                    src="https://i.im.ge/2023/02/23/7Og4GJ.1.png"
                    width={800}
                    height={700}
                    alt="High-End Project"
                  />
                </div>
              </div>

              <div className={styles.column2d}>
                <h2 className={styles.titled}>MedicalRoom</h2>

                <div className={styles.descriptiond}>
                  <p className={styles.textd}>
                    MedicalRoom is a blockchain-based medical record system that
                    provides a secure and efficient way to store, share, and
                    access patient data. By leveraging the immutability and
                    decentralization of blockchain technology, this system
                    ensures the integrity and confidentiality of sensitive
                    medical information, while streamlining workflows and
                    reducing costs for healthcare providers. Our system is
                    created to revolutionize the healthcare industry, improving
                    patient outcomes and driving innovation.
                  </p>
                  <button className={styles.buttond}>
                    Explore MedicalRoom
                  </button>
                </div>
              </div>
            </div>
          </div>

          <section id="team">
            <h2 className={styles.titled}>Meet Our Team</h2>
            <div className={styles.teamcontainer}>
              <div className={styles.teammember}>
                <Image
                  src="https://i.im.ge/2023/02/12/aYQE21.307881578-900579777633670-5090738587803987001-n.jpg"
                  alt="Team Member 1"
                  width={200}
                  height={200}
                />
                <h3>Mohamed Essam</h3>
                <p>Frontend</p>
              </div>
              <div className={styles.teammember}>
                <Image
                  src="https://i.im.ge/2023/02/23/7FGePL.27709855-2116696651883892-1952015847078010882-o.jpg"
                  alt="Team Member 2"
                  width={300}
                  height={200}
                />
                <h3>Adham Ali</h3>
                <p>web3 Fullstack</p>
              </div>
              <div className={styles.teammember}>
                <Image
                  src="https://i.im.ge/2023/02/23/7OQvQh.WhatsApp-Image2-2023-02-23-at-3-52-45-PM.jpg"
                  alt="Team Member 3"
                  width={300}
                  height={200}
                />
                <h3>Ahmed Ali</h3>
                <p>Backend</p>
              </div>
              <div className={styles.teammember}>
                <Image
                  src="https://i.im.ge/2023/02/23/7OTTup.WhatsApp-Image-2023-02-23-at-3-55-51-PM-1.jpg"
                  alt="Team Member 3"
                  width={300}
                  height={200}
                />
                <h3>Youssef Gamal</h3>
                <p>UI and Frontend</p>
              </div>{" "}
              <div className={styles.teammember}>
                <Image
                  src="https://i.im.ge/2023/02/23/7OoY7y.WhatsApp-Image-2023-02-23-at-4-01-17-PMs.jpg"
                  alt="Team Member 3"
                  width={300}
                  height={200}
                />
                <h3>Mohamed Khaled</h3>
                <p>API's and graph indexing</p>
              </div>
            </div>
          </section>
        </main>
      </div>
      <Footer />
    </>
  );
}
